# Frontend-specific Render configuration
# Use this if deploying frontend separately

services:
  - type: web
    name: coaching-frontend-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://coaching-backend-api.onrender.com/api
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://coaching-backend-api.onrender.com 