# Executive Coaching Platform - Render Blueprint Configuration
# Updated: Using external Redis or in-memory cache
services:
  # Backend API Service
  - type: web
    name: coaching-backend
    env: node
    repo: https://github.com/nbrain-team/michael-training
    buildCommand: cd backend && npm install --production=false && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: coaching-db
          property: connectionString
      - key: REDIS_URL
        sync: false  # Optional - set if using external Redis
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: FRONTEND_URL
        value: https://coaching-frontend.onrender.com
    healthCheckPath: /health

  # Frontend Next.js Service
  - type: web
    name: coaching-frontend
    env: node
    repo: https://github.com/nbrain-team/michael-training
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://coaching-backend.onrender.com/api
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://coaching-backend.onrender.com

  # AI Engine Service
  - type: web
    name: coaching-ai-engine
    env: node
    repo: https://github.com/nbrain-team/michael-training
    buildCommand: cd ai-engine && npm install --production=false && npm run build
    startCommand: cd ai-engine && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false  # Optional - set if using external Redis
    healthCheckPath: /health

databases:
  # MongoDB Database
  - name: coaching-db
    databaseName: coaching
    user: coaching_user 